### ISSUE TITLE
Correct Answer(s)

### ISSUE THREAD

**Issue by zh4r11** [LarryBattle/jQuizMe#17]
Hey Larry. I am interested in your jQuizMe-2.2.1.js file. But, I found one problem when trying to change some code. So, can you help me?

I have tried to eliminate the "Correct Answer" section. But it hasn't been successful.

**Comment by LarryBattle** [comment]
Did you try using one of these options?

```js
$(element).jQuizMe( wordList, {
    alwaysShowAnsInfo: false, // Shows answer information when correct or incorrect answer are received.
    showAnsInfo: false, // If provided, show the answers information after each question.
    showWrongAns: false,  // If answer is wrong, then show the user's wrong answer after each question.
});
```

If none of those solutions work for you then I don't think this is supported.

To get rid of the correct answer section try modifying jQuizme.
Try setting this to `true` and see what happens.
https://github.com/LarryBattle/jQuizMe/blob/v2.2/jQuizMe-2.2.js#L447

from:
```js
displayAnsResult();
```
to:
```js
displayAnsResult(true);
```

You can also modify this to never show the correct answer.
https://github.com/LarryBattle/jQuizMe/blob/v2.2/jQuizMe-2.2.js#L719
From:
```js
show = ( isUserAnsCorr ) ? lang.ans.praise :
								( lang.ans.corrAns + '<br/>' + getStrArrOfSeeableHTML( currAns, toUni ).join( '<br/>' ) );
```
to:
```js
show = ( isUserAnsCorr ) ? lang.ans.praise :
								( lang.ans.corrAns + '<br/>' + getStrArrOfSeeableHTML( currAns, toUni ).join( '<br/>' ) );
```
to: 
```js
show = "";
if( isUserAnsCorr ){
    show = lang.ans.praise;
}
```
Hope that helps
